# Generated by Django 5.1.4 on 2025-02-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expance_track_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserReg',
        ),
    ]
