# Generated by Django 5.1.4 on 2025-02-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expance_track_app', '0003_expence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expence',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expence',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expence',
            name='expance_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
